---
site_name          : {{ cookiecutter.project_name }}
site_description   : {{ cookiecutter.project_description }}
repo_url           : https://github.com/{{ cookiecutter.repository_user }}/{{ cookiecutter.repository_name }}

theme              :
  name: material

nav                :
  - Home: index.md
  - Changelog: CHANGELOG.md
  - Contributing:
      - Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - API: mkapi/api/src/{{ cookiecutter.package_name }}|strict
  - About:
      - License: LICENSE.md

plugins            :
  - search
  - mkapi
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: dev.mkdocs:on_pre_build

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.highlight
